# Generated by Django 3.1.1 on 2020-11-22 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChPro', '0003_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='questions',
            new_name='saQuestions',
        ),
    ]
