# Generated by Django 3.1.1 on 2020-11-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChPro', '0004_auto_20201122_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
